name: eslint
on: 
  schedule:
    - cron: '*/15 * * * *'
  pull_request:
    types:
      - opened
      - synchronize
      - closed
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: bradennapier/eslint-plus-action@v3.4.2
      with: 
        reportIgnoredFiles: true
        issueSummaryOnlyOnEvent: true