# This is a basic workflow to help you get started with Actions

name: Automated Tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  push:
    branches:
      - '!develop'
      - '*'
  pull_request:
    branches:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
          
  unittests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Coverage Report
        run: |
          npm ci
          npm test -- --coverage
        env:
          CI: true
     
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          
  eslint-plus:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
        env: 
          CI: true
      - uses: Face-the-Facts/eslint-plus-action@v3.4.2
        with:
          issueSummaryType: full
          extensions: .tsx
          configFile: .eslintrc.json
          reportIgnoredFiles: true

  
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
        env:
          CI: true
      - name: Run eslint
        run: |
            npx eslint ./src --ext .tsx --max-warnings 0
      #- id: eslint
      #- name: Run ESLint
      #  run: |
      #    # Install dependencies
      #    npm ci
      #    # Run eslint with max warnings of 0
      #    npx eslint ./src --ext .tsx --max-warnings 0
      #  env:
      #    CI: true

